var price1 = 31;
var price2 = 10;
var tomatoPrice = price1 + price2;
// console.log(tomatoPrice);
var firstName = "Jennie";
var lastName = "kim";
// var fullName = firstName + lastName;
// var fullName = firstName + "X" + lastName;
var fullName = firstName + " " + lastName;
console.log(fullName);
